version: "3.7"
services:
    backend:
        build: ./backend
        restart: always
        ports: ["5000:5000"]
        volumes: ['./backend:/backend']

    frontend:
        build: ./frontend
        restart: always
        ports: ["3000:3000"]
        volumes: ['./frontend:/frontend']