POST http://sitesranking-backend.herokuapp.com/get_criteria
Content-Type: application/json

{
    "selectedCriteriaNum": 3,
    "expertsMark": [[[1, 4, 3, 5, 2, 5, 3, 1, 1],
                    [2, 2, 1, 1, 4, 3, 5, 5, 4],
                    [3, 3, 3, 5, 1, 2, 2, 2, 5],
                    [4, 4, 3, 3, 2, 1, 2, 5, 5]],
                    [[1, 4, 3, 5, 2, 5, 3, 1, 1],
                    [2, 2, 1, 1, 4, 3, 5, 5, 4],
                    [3, 3, 3, 5, 1, 2, 2, 2, 5],
                    [4, 4, 3, 3, 2, 1, 2, 5, 5]],
                    [[1, 4, 3, 5, 2, 5, 3, 1, 1],
                    [2, 2, 1, 1, 4, 3, 5, 5, 4],
                    [3, 3, 3, 5, 1, 2, 2, 2, 5],
                    [4, 4, 3, 3, 2, 1, 2, 5, 5]]]
}

###
POST  http://sitesranking-backend.herokuapp.com/get_score
Content-Type: application/json

{
    "criteriaWeight": 
    [0.6445132902312491, 0.5720885236510244, 0.5989457300495843],  
    "expertsWeight": [1],
    "userRatingScore": [
        [83, 61, 98]
    ]

}