POST http://localhost:5000/get_criteria
Content-Type: application/json

{
    "selectedCriteriaNum": 3,
    "expertsMark": [[[1, 4, 3, 5, 2, 5, 3, 1, 1],
                    [2, 2, 1, 1, 4, 3, 5, 5, 4],
                    [3, 3, 3, 5, 1, 2, 2, 2, 5],
                    [4, 4, 3, 3, 2, 1, 2, 5, 5]],
                    [[1, 4, 3, 5, 2, 5, 3, 1, 1],
                    [2, 2, 1, 1, 4, 3, 5, 5, 4],
                    [3, 3, 3, 5, 1, 2, 2, 2, 5],
                    [4, 4, 3, 3, 2, 1, 2, 5, 5]],
                    [[1, 4, 3, 5, 2, 5, 3, 1, 1],
                    [2, 2, 1, 1, 4, 3, 5, 5, 4],
                    [3, 3, 3, 5, 1, 2, 2, 2, 5],
                    [4, 4, 3, 3, 2, 1, 2, 5, 5]]]
}

###
POST  http://localhost:5000/get_score
Content-Type: application/json

{
    "criteriaWeight": [
    2.384322878026267,
    2.4804351331952113,
    2.4262633168162773
    ],  
    "expertsWeight": [
        0.3333333333333333,
        0.3333333333333333,
        0.3333333333333333
    ],
    "userRatingScore": [
        [31, 2, 3],
        [23, 45, 56]
    ]

}